# Generated by Django 3.1.7 on 2021-03-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='business',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='reviews.Discipline'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
